import pandas as pd
from snakemake.utils import validate


configfile: "config/config.yaml"


validate(config, schema="../schema/config.schema.yaml")

manifest = pd.read_table(config["manifest"], sep="\t").set_index("analysis", drop=False)

TARGETS = "results/{}/{}/{}/{}/output.tsv".format(
    manifest["analysis"],
    manifest["dataset"],
    manifest["tool"],
    manifest["regression_model"],
)


rule all:
    """
    phony target to deploy all jobs
    """
    input:
        TARGETS,


include: "rules/minimac4.smk"
include: "rules/plink2.smk"
