# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.*js$|^.*css$|^.*svg$|^.*html$"
repos:
## general purpose linting and formatting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    exclude: >
      (?x)^(
      .*\.js
      .*\.css
      .*\.svg
      )$

## Python support
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://gitlab.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    exclude: ^report/
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort

## Snakemake linting
- repo: https://github.com/snakemake/snakefmt
  rev: v0.6.1
  hooks:
  - id: snakefmt

## R support
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2
  hooks:
  - id: style-files
  - id: parsable-R
  - id: no-browser-statement
  - id: lintr
    verbose: true
