imputed_datasets:
  - type: impute2
    snp_major: yes
    gen-filename: "Name of IMPUTE2 gen file to be processed"
    sample-filename: "Name of IMPUTE2 sample file to be processed"


# - type: mach
#   snp_major: no

# - type: minimac
# - snp_major: no
