#!/bin/bash
###SNPTEST mode
../statgen-mi.out --mi-imputed-dataset-config ./mi.imputeddataset.config --mi-output-prefix result --mi-program-config ./mi.program.config --mi-submission-queue-config ./mi.queue.config --program-run-type snptest --imputed-dataset-type impute2 --impute2-gen-filename test.gen --impute2-sample-filename test.sample --snptest-gen-prefix testoutput.draw --snptest-gen-suffix .gen.gz --snptest-sample-prefix testoutput.draw --snptest-sample-suffix .sample --snptest-frequentist 1 --snptest-pheno pheno --snptest-method score --snptest-autocorrect-traits --snptest-output-prefix test-snptest-results-draw --snptest-output-suffix .results --mi-queue-type none
../statgen-mi.out --mi-imputed-dataset-config ./mi.imputeddataset.config --mi-output-prefix result --mi-program-config ./mi.program.config --mi-submission-queue-config ./mi.queue.config --program-run-type snptest --imputed-dataset-type impute2 --impute2-gen-filename test.gen --impute2-sample-filename test.sample --snptest-gen-prefix testoutput.draw --snptest-gen-suffix .gen.gz --snptest-sample-prefix testoutput.draw --snptest-sample-suffix .sample --snptest-frequentist 1 --snptest-pheno pheno --snptest-method score --snptest-autocorrect-traits --snptest-output-prefix test-snptest-results-draw --snptest-output-suffix .results --mi-queue-type none --mi-clean



#PLINK mode
../statgen-mi.out --mi-imputed-dataset-config ./mi.imputeddataset.config --mi-output-prefix result-plink --mi-program-config ./mi.program.config --mi-submission-queue-config ./mi.queue.config --program-run-type plink --imputed-dataset-type impute2 --impute2-gen-filename test.gen --impute2-sample-filename test.sample --plink-bfile-prefix testoutput.plink.draw --plink-bfile-suffix .whatever --plink-pheno-prefix testoutput.plink.draw --plink-pheno-suffix .pheno --plink-logistic --plink-pheno-name pheno --plink-vif 1000 --plink-out-prefix test-plink-results-draw --plink-out-suffix .results --mi-queue-type none
../statgen-mi.out --mi-imputed-dataset-config ./mi.imputeddataset.config --mi-output-prefix result-plink --mi-program-config ./mi.program.config --mi-submission-queue-config ./mi.queue.config --program-run-type plink --imputed-dataset-type impute2 --impute2-gen-filename test.gen --impute2-sample-filename test.sample --plink-bfile-prefix testoutput.plink.draw --plink-bfile-suffix .whatever --plink-pheno-prefix testoutput.plink.draw --plink-pheno-suffix .pheno --plink-logistic --plink-pheno-name pheno --plink-vif 1000 --plink-out-prefix test-plink-results-draw --plink-out-suffix .results --mi-queue-type none --mi-clean
